### ISSUE TITLE
better solution for nested if statements

### ISSUE THREAD

**Issue by AdyPolyCode** [viktorsynek/alarm#1]
https://github.com/viktorsynek/alarm/blob/ed19711f76b7076edb3fc9b23d19d8a4bba7fdb7/main.py#L37

![sol](https://user-images.githubusercontent.com/76212893/172231206-b2e86f26-3525-4cf0-a1ff-6f8955c66c7b.png)

**Comment by viktorsynek** [comment]
thanks, I'll consider implementing it!
